# Generated by Django 4.2.3 on 2023-07-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mvmodel',
            name='director',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mvmodel',
            name='genre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mvmodel',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mvmodel',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
